tomasstolker/species

docs/species.data.rst, species/data/database.py, species/data/vega.py
Added compatibility of the `add_object` function of `Database` with the GRAVITY format. The FITS cube with the spectrum and covariance matrix can be provided twice, instead of using a separate file for the spectrum and covariances. For example:
``database.add_object('planet name', distance=(20., 0.1), app_mag=None, spectrum={'GRAVITY': ('data.fits', data.fits')})``
Also additional output is printed.
=> Compatibility of add_object with GRAVITY format

README.rst, docs/about.rst, requirements.txt, species/analysis/fit_model.py, species/analysis/fit_planck.py, species/analysis/fit_spectrum.py, species/data/companions.py, species/data/database.py, species/data/exo_rem.py, species/plot/plot_mcmc.py, species/read/read_calibration.py, species/read/read_model.py, species/util/data_util.py, species/util/phot_util.py, species/util/read_util.py, test/test_read/test_calibration.py, test/test_read/test_isochrone.py, test/test_read/test_model.py, test/test_read/test_planck.py
- Updated dependencies in `requirements.txt`.
- Added the `run_multinest` function in `FitModel` to use the nested sampling implementation of `MultiNest` for the parameter estimation. This can be in particular useful to sample multimodal distributions.
- Some changes in `add_samples` to make it compatible with both the MCMC and nested sampling results.
- Added errors in case the burnin of the MCMC samples is larger than the number of steps.
- Changed the group name of the fit results from `results/mcmc` to `results/fit`.
- Improved compatibility with the Exo-REM models, which are now resampled to a constant resolution of 1000 and available here:
https://people.phys.ethz.ch/~ipa/tstolker/exorem.tgz
Note that there is an issue with this set of spectra above ~1600 K because not all models …
=> Parameter estimation with nested sampling

.readthedocs.yml, docs/conf.py, docs/requirements.txt, docs/tutorials/synthetic_photometry.ipynb, species/analysis/fit_model.py, species/data/vlm_plx.py
The autodocs were not building due to the external Fortran library (`MultiNest`, which can not be installed on `readthedocs`) that is required by `PyMultiNest`. This was solved by adding a `try ... except` at the import of `PyMultiNest`. So the API documentation should be available again!
https://species.readthedocs.io/en/latest/modules.html
=> Bug fix building of the autodocs

species/analysis/fit_model.py, species/analysis/fit_planck.py, species/analysis/fit_spectrum.py, species/data/companions.py, species/plot/plot_spectrum.py, species/read/read_object.py
Fitting of duplicate filter names is now supported by `FitModel` and `FitSpectrum` and was already supported by `FitPlanck`.
=> Support for duplicate filter names in FitModel and FitSpectrum

species/analysis/fit_model.py, species/analysis/fit_planck.py, species/analysis/fit_spectrum.py, species/data/companions.py, species/plot/plot_mcmc.py, species/read/read_model.py, species/read/read_planck.py, species/util/plot_util.py
- Bug fix of for loop indices in likelihood function with the use of duplicate filter names.
- Type hints and type checks added in `FitPlanck`.
- Prior added to `FitPlanck` when multiple blackbody components are fitted to enforce the temperature and radii to decrease and increase, respectively.
- Added `run_multinest` to `FitPlanck` to use nested sampling for the parameter estimation, complementing MCMC with `run_mcmc`.
- The `inc_luminosity` parameters also supports results from `FitPlanck` with multiple blackbody components.
- The luminosity is added to the `ModelBox` from `ReadPlanck.get_spectrum`.
- Updated axis labels for plots.
=> Nested sampling with FitPlanck

species/plot/plot_color.py, species/plot/plot_mcmc.py, species/plot/plot_spectrum.py
- The `legend` parameter in `plot_spectrum` can be a list with two legend values (either a location or kwargs dictionary) to separate the model and data legend. Otherwise, a single legend is created with backward compatibility.
- Type checks added to `plot_spectrum`.
=> Separation of data and model legend in plot_spectrum

docs/tutorials.rst, species/core/setup.py, species/data/ames_cond.py, species/data/ames_dusty.py, species/data/btnextgen.py, species/data/btsettl.py, species/data/btsettl_cifist.py, species/data/database.py, species/data/drift_phoenix.py, species/data/exo_rem.py, species/data/petitcode.py, species/plot/plot_mcmc.py, species/plot/plot_spectrum.py, species/read/read_model.py, species/util/plot_util.py
- Removed the try-except when model spectra are imported and (optionally) resampled. With the new version of `spectres` the error was changed into a warning and a `fill` value (set to NaN in `species`) is used outside the wavelength range of the input data.
- Added a timeout to `SpeciesInit` for poor internet connections.
- Added the luminosity ratio to the posterior plot when fitting two blackbody components.
=> Updated use of spectres and timeout added to SpeciesInit

species/data/ames_cond.py, species/data/database.py, test/test_read/test_isochrone.py, test/test_read/test_model.py
- Changed the download location of the AMES-Cond spectra to the ETH/IPA server because https://phoenix.ens-lyon.fr/Grids is no longer available. The `add_ames_cond` function has been updated.
- The original spectra have been resampled to R=2000 from 0.5 to 40 um.
- The resampled spectra have been stored with regular units and the atmosphere parameters are included in the filename.
- AMES-Dusty and BT-NextGen, which are also downloaded from the ens-lyon.fr page, will be migrated in another PR. BT-Settl is already being downloaded from the ETH/IPA storage.
=> Changed the storage location of the AMES-Cond spectra

species/analysis/fit_model.py, species/data/database.py, species/data/dust.py, species/plot/plot_color.py, species/plot/plot_mcmc.py, species/plot/plot_spectrum.py, species/read/read_model.py, species/util/dust_util.py, species/util/plot_util.py, species/util/read_util.py
- Added support for fitting extinction parameters based on a power-law size-distribution of silicate grains. The cross-sections are interpolated from a pre-calculated grid with the maximum grain size (`powerlaw_max`), the power-law exponent (`powerlaw_exp`), and the V band extinction (`powerlaw_ext`) as free parameters. The minimum grain size is fixed to 1 nm since the results are not sensitive to the minimum grain size as long as it is much smaller than the wavelength.
- The extinction parameters for the log-normal size distribution have been changed from `dust_` to `lognorm_` without backward compatibility.
- The `add_dust` method of `Database` downloads and adds the pre-calculated cross sections.
- `ReadModel`, `plot_extinction`, `plot_size_distributions`, and `plot_util` have been …
=> Extinction parameters for a power-law size distribution of grains

species/analysis/photometry.py, species/data/database.py, species/data/filters.py, species/read/read_filter.py, test/test_analysis/test_photometry.py, test/test_read/test_filter.py
- Added support for filters from photon-counting detectors. The detector type determines if an additional wavelength factor is included in the integral for the synthetic photometry.
- For filters that are automatically fetched from the SVO webpage, the detector type is read from the data.
- For filters that are manually added with `add_filter`, the detector type needs to be set with the `detector_type` parameter (default: `'photon'`).
- The detector type is stored in the database as the `det_type` attribute with the filter profile.
- The `SyntheticPhotometry` checks the detector type when calculating average fluxes.
- The `download_filter` function has been updated.
- Added the `detector_type` method to `ReadFilter` which returns the detector type.
- Added unit tests for the …
=> Support for filters from photon-counting detectors

species/data/btnextgen.py, species/data/database.py
The BT-NextGen spectra have been resampled to R=2000 from 0.1 to 50 micron, and their download location has been changed since https://phoenix.ens-lyon.fr/Grids/ is offline. Only spectra with Teff < 30000 K and 3 <= log(g) <= 5 have been used, with 3 grid point for [Fe/H]. With the resampling, the TAR file is only 368 MB, so it is also much faster to download and process. The `add_btnextgen` function had been updated.
=> Resampled the BT-NextGen spectra and changed their download location

species/plot/plot_mcmc.py, species/util/plot_util.py
The `title_fmt` parameter of `plot_posterior` has been changed with backward compatibility. The format of the titles above the histograms in the posterior plots can be set for each parameter individually by providing a list with formats instead of a single string.
=> Support for different formats of the histogram titles of plot_posterior

species/analysis/fit_model.py, species/data/database.py, species/data/petitcode.py
The clear and cloudy petitCODE spectra of the hot grid (Teff = 1000-2000 K) are now publicly available and downloaded by `species` from https://people.phys.ethz.ch/~ipa/tstolker/. Therefore, the argument of `data_folder` is no longer required with the `add_model` method. The `data_folder` parameter will be deprecated in a future release.
=> petitCODE hot spectra are publicly available

species/plot/plot_mcmc.py
This should fix #31. I replaced `:` with `...` to ensure that only the last axis (parameters) is affected by selection. This prevents the 3D `run_mcmc` samples to be truncated to 4-5 samples per walkers. It should not affected `run_multinest` which will behave as before.
=> Use only last axis for parameter selection in samples

species/data/atmo.py, species/read/read_spectrum.py, species/util/dust_util.py, species/util/read_util.py
Improved sampling of the log-normal distribution in `dust_util.log_normal_distribution`. The `interval` method is used to calculate the grain radius interval that contains 99.999% of the distribution.
=> Improved sampling of the log-normal distribution

README.rst, docs/conf.py, docs/configuration.rst, species/analysis/fit_model.py, species/data/companions.py, species/data/database.py, species/plot/plot_color.py, species/plot/plot_mcmc.py, species/plot/plot_spectrum.py, species/util/plot_util.py, species/util/read_util.py
- Improved approach for fitting the error inflation of spectra in `FitModel`. Instead of fitting a constant, the free parameter is a scaling relative to the model fluxes (see Piette & Madhusudhan 2020). The use of the error inflation parameter has not changed but in this case typically requires a `bound` value between 0 and 1. Both `run_multinest` and `run_mcmc` have been updated.
- The optional `model` parameter has been added to `update_spectra` since the error inflation requires calculating the model spectrum.
- Bug fix with the use of fixed parameters in `FitModel` since the calibration and extinction parameters were not fixed.
- The `deredden` parameter in `add_object` can also be a float (instead of dictionary), in which case the same dereddening is applied to all input data.
- When …
=> Improved error inflation, new log-normal cross sections, and some minor things

species/read/read_calibration.py
The `spec_res` parameter had been added to the `resample_spectrum` method of `ReadCalibration`. By setting this parameter, the spectrum is smoothed with a Gaussian kernel to the requested resolution before the wavelengths are resampled. When setting `spec_res=None` (default), no smoothing is applied and the wavelengths are only resampled.
=> Added spec_res parameter to ReadCalibration.resample_spectrum

.readthedocs.yml, README.rst, docs/overview.rst, species/__init__.py, species/analysis/empirical.py, species/data/database.py, species/data/irtf.py, species/data/kesseli2017.py, species/data/leggett.py, species/data/spex.py, species/data/vlm_plx.py, species/plot/plot_empirical.py, species/read/read_spectrum.py, species/util/data_util.py, species/util/plot_util.py, species/util/read_util.py
- Added the `analysis.empirical.CompareSpectra` class for comparing spectra.
- Currently, `CompareSpectra` has one method, `spectral_type`, which can be used for comparing a spectrum with a library of spectra (which can be added to the database with `add_spectrum`) to find the best matching spectral type.
- The `spectral_type` method has parameters to test different A_V and RV values although the latter is perhaps not needed given the typical spectral resolution.
- Support for the SDSS spectra from Kesseli et al. (2017), which are added as `add_spectrum('kesseli+2017')`.
- Added the `plot_statistic` and `plot_empirical_spectra` functions for plotting the results from `CompareSpectra.spectral_type`.
=> Tools for empirical spectral analysis

species/analysis/fit_model.py, species/read/read_model.py
- When running `FitModel` with MPI multiprocessing (e.g. with `mpirun`), an error occurred when the samples are stored in the database after `MultiNest` or `UltraNest` has finished. While multiple processes can read from the database at the same time, writing to the database is not possible. As a fix, the rank of the processes is checked and the `add_samples` method is executed only by rank number 0. To make use of the MPI support, it is also required to manually install `mpi4py`.
- Errors are added in `ReadModel` when extinction is applied but the chosen wavelength range goes beyond the wavelength range of the available dust cross sections.
=> Check MPI rank when storing FitModel

species/__init__.py, species/analysis/emission_line.py, species/analysis/fit_model.py, species/data/companions.py, species/data/database.py, species/plot/plot_comparison.py
- Support for making spectra of directly imaged companions easily available (see `data.companions`). Currently available spectra can be listed with `Database.list_companions` and the spectra are added (together with other data) to the database with `Database.add_companion` (e.g. `add_companion('beta Pic b')`).
- Try-except was added to the imports of `UltraNest`, which was causing an error in case `cython` was not correctly installed ([see issue](https://github.com/JohannesBuchner/UltraNest/issues/29)).
- Some minor maintenance.
=> Spectra of directly imaged planets and brown dwarfs

README.rst, docs/installation.rst, docs/species.data.rst, docs/tutorials/color_magnitude_narrowband.ipynb, docs/tutorials/spectral_library.ipynb, requirements.txt, species/analysis/compare_spectra.py, species/analysis/photometry.py, species/data/allers2013.py, species/data/bonnefoy2014.py, species/data/companions.py, species/data/database.py, species/data/irtf.py, species/data/kesseli2017.py, species/data/spex.py, species/plot/plot_color.py, species/plot/plot_comparison.py, species/plot/plot_spectrum.py, species/read/read_model.py, species/read/read_spectrum.py, species/util/dust_util.py, species/util/plot_util.py
- Support for low-gravity spectra from Bonnefoy et al. (2014) and Allers & Liu (2013).
- Further development of `analysis.compare_spectra` and `plot.plot_comparison`.
- Support for disk parameters in `ReadModel.get_data`.
- Added `leg_param` parameter in `plot_spectrum` for model parameters to include in the legend.
- Changed `Database.add_spectrum` to `Database.add_spectra` (`add_spectrum` will be removed in a future release).
- Maintenance of the code and documentation.
=> Empirical low-gravity spectra and development of comparison tools

.codecov.yml, README.rst, docs/database.rst, docs/installation.rst, species/analysis/fit_model.py, species/analysis/retrieval.py, species/core/constants.py, species/core/init.py, species/data/allers2013.py, species/data/companions.py, species/data/database.py, species/data/vega.py, species/plot/plot_comparison.py, species/plot/plot_mcmc.py, species/plot/plot_retrieval.py, species/read/read_radtrans.py, species/util/data_util.py, species/util/plot_util.py, species/util/retrieval_util.py, tests/test_read/test_spectrum.py
- Check prior range with respect to grid boundaries when using `FitModel`
- Check if both data covariances and Gaussian process parameters are included (while only one of them is required) when using `FitModel`
- Support for both the official petitRADTRANS package and the fork from https://gitlab.com/tomasstolker/petitRADTRANS. The latter contains additional features for cloud parameterizations and retrieval of physically-consistent temperature profiles
- `convective_flux` function in `retrieval_util` for calculating the convective flux as function of pressure
- Fitting the turnover wavelength (`opa_knee`) towards the Rayleigh-Jeans slope for parameterized cloud opacities
- Fitting the mixing length (`mix_length`) of the convective flux when using the the `check_flux` parameter of …
=> New features for AtmosphericRetrieval

species/__init__.py, species/analysis/fit_model.py, species/analysis/retrieval.py, species/core/box.py, species/data/database.py, species/plot/plot_color.py, species/plot/plot_comparison.py, species/plot/plot_mcmc.py, species/plot/plot_retrieval.py, species/plot/plot_spectrum.py, species/read/read_model.py, species/read/read_radtrans.py, species/util/phot_util.py, species/util/plot_util.py, species/util/read_util.py, species/util/retrieval_util.py, tests/test_read/test_object.py
- Support for fitting data of blended stars/companions with `FitModel`. Prior boundaries can be provided twice for each atmospheric parameter. If a single range is provided, the parameters are assumed to be the same for both components. The latter can be useful to model a single object with a combination of two parameters (e.g. to account for atmospheric asymmetries) while some other parameters have the same value (e.g. log(g), radius). Functions such as `get_mcmc_spectra`, `multi_photometry`, and `get_residuals` are compatible with blended atmosphere parameters.
- Added the `binary_spectrum` method to `ReadModel`, which is similar to `get_model`, but returns a `ModelBox` for a `model_param` dictionary with blended atmosphere parameters.
- In addition to fitting an error inflation for a …
=> Support for fitting blended stars/companions with FitModel

species/analysis/retrieval.py, species/data/database.py, species/plot/plot_retrieval.py, species/read/read_radtrans.py, species/util/plot_util.py, species/util/retrieval_util.py
- Support for retrieving a weighted combination of two sedimentation parameters (`fsed_1` and `fsed_2`) to account for horizontal cloud variations. Currently only implemented for the parametrized / power-law cloud opacities.
- Changed the `gamma_r` parameter in `AtmosphericRetrieval` to `log_gamma_r` with a log-uniform sampling.
- Added the `pt_profile` parameter to `ReadRadtrans` for providing an array with the P-T profile (set also `pressure_grid="manual"`) as input instead of using one of the paramterizations. 
- Updated the `petitcode_param` method of `Database` for converting the best retrieved parameters to input for petitCODE for calculating the self-consistent temperature profile.
- Style improvements and some minor maintenance.
=> Retrieving a weighted combination of two clouds and some small updates

species/analysis/fit_model.py, species/data/database.py, species/plot/plot_mcmc.py, species/read/read_model.py, species/util/dust_util.py
This PR addresses issue #65 and implements the following changes:
- The `interp2d` interpolation function from `scipy` is deprecated. It was used in the `dust_util` module where it has been replaced with the recommended `RegularGridInterpolator`. This gives slightly different but comparable results to `interp2d`.
- Optimization for interpolating dust cross sections for spectrum wavelengths, not requiring a `for` loop.
- Added comments to the `apply_lognorm_ext` and `apply_powerlaw_ext` methods in `ReadModel`.
- Fixed a bug when adding the value of `lbl_opacity_sampling` that is used with `AtmosphericRetrieval` to the database.
=> Changed use of interp2d to RegularGridInterpolator

species/data/companion_data/companion_data.json
This PR adds available photometry and host star properties for the companion GJ 758 B.
=> add companion data for GJ 758 B

species/plot/plot_mcmc.py, species/util/radtrans_util.py, species/util/retrieval_util.py
Hi Tomas, these are a few very small bugs I found in running some retrievals this past month. 
When plotting a free chemistry retrieval, there was no enumerator in the loop so the C/H, O/H, and C/O posteriors were returned with =0. 
When global_fsed was set false, and then post processed to make plots, it would give a KeyError: "fsed", which I handled with the try/except statement (not sure if there is a different way you'd prefer to handle that). 
The mmw wasn't established in the chemical equilibrium portion of the clear spectrum generator.
=> Small fixes

species/fit/retrieval.py
For cases where there is dense photometry but not spectroscopy, one may still want to run a retrieval. This tiny bugfix patches an instance where a breaking error would be thrown by setup_retrieval when inc_spec=False and the list data_spec_res is empty.
=> small bugfix in setup_retrieval without spectra

species/data/model_data/custom_model.py
A small quick fix: I was encountering a key/parameter error when trying to use add_custom model and I realized it was because the `add_custom_model_grid` and `stort_data` had different lengths of parameter dictionaries.
=> add co_iso to custom model to avoid error

species/data/companion_data/companion_data.json
Hi Tomas! This addition includes the 3-5 micron photometry of the HR 8799 and 51 Eri planets from our recent JWST paper (https://doi.org/10.3847/1538-3881/adb1c6).
=> Add nircam bar photometry from Balmer et al. 2025b
